### PR TITLE
breakaway from buckyos

### PR DESCRIPTION
**Pull request by streetycat**
breakaway from buckyos，reference: https://github.com/buckyos/buckyos/pull/17

### CODE REVIEW

**Comment by waterflier** [comment]
I suggest that when choosing terminology, we should use idiomatic expressions. If it’s a custom concept, the term can be longer. We might consider preparing a glossary of terms. The following terms, as they stand, require understanding the code to grasp their meaning, and I think they could easily be misunderstood by other readers.

```rust
task_unique_name  // Does this refer to task_uuid?
engine.on_push_new_checkpoint  // What does "push" mean here? Does it mean "on_resume"?
let source_reader = make_source_reader  // Is "make" the same as "create"?
```

Regarding *Checkpoint*, the most complex component currently seems to be *CheckPointMetaBuilder*. This can be constructed by understanding the checkpoint information saved on the target and combining it with the Source based on an already completed task ID. Who is responsible for implementing *CheckPointMetaBuilder* (backup_source? backup_target? or backup_engine?)? Does it need to be extended?

I don't understand the relationship between `source_reader.get_next_item` and incremental backup.

As for `target.on_abort`, I think we need to distinguish between `target_client` (target_plugin) and `target_service`. I have the impression that this code belongs to `target_plugin`.

I don't understand the significance of `engine.export()`. I don't think task export is a key requirement at this stage.

**Comment by streetycat** [comment]
> I suggest that when choosing terminology, we should use idiomatic expressions. If it’s a custom concept, the term can be longer. We might consider preparing a glossary of terms. The following terms, as they stand, require understanding the code to grasp their meaning, and I think they could easily be misunderstood by other readers.
> 
> ```rust
> task_unique_name  // Does this refer to task_uuid?
> engine.on_push_new_checkpoint  // What does "push" mean here? Does it mean "on_resume"?
> let source_reader = make_source_reader  // Is "make" the same as "create"?
> ```
> 
> Regarding _MetaBuilder_, the most complex component currently seems to be _CheckPointMetaBuilder_. This can be constructed by understanding the checkpoint information saved on the target and combining it with the Source based on an already completed task ID. Who is responsible for implementing _CheckPointMetaBuilder_ (backup_source? backup_target? or backup_engine?)? Does it need to be extended?
> 
> I don't understand the relationship between and incremental backup.`source_reader.get_next_item`
> 
> As for , I think we need to distinguish between (target_plugin) and . I have the impression that this code belongs to .`target.on_abort``target_client``target_service``target_plugin`
> 
> I don't understand the significance of . I don't think task export is a key requirement at this stage.`engine.export()`

Thank you very much for your excellent comments. I have submitted a new document with the following changes:
1. Added the main pseudocode for the `source` module.
2. Assigning a `uuid` to a `task` is a good idea, and I have also added a `friendly_name` to the task;
   * Previously, the `task_unique_id` was essentially a unique `friendly_name`, but it could lead to issues with duplicate tasks. For example:
     After information loss, it might be difficult for the user to choose a historically unique name again. In this case, if historical data is restored, it could result in duplicate names.
3. Changed `on_push_new_checkpoint` to `start_transfer_checkpoint`, which should be easier to understand.
4. Renamed `make_source_reader` to the Rust language's commonly used constructor naming style `..._from`, changing it to `source_reader_from_url`.
5. For `incremental backup`, here is an illustration:
   1. Enumerate all objects to be backed up from the `source` using `source_reader.get_next_item`.
   2. For each traversed object, use `prev_checkpoints.get_stat(item.path)` to find its attributes in the old version. If there are changes, add it to `CheckPointMeta`; otherwise, discard it.
      * This part is quite complex. For example, folders need to be compared recursively, and if an object only has attribute updates, a single log entry is sufficient.
   3. Then use `prev_checkpoints.get_next_item()` to find all objects in the old version and compare them with the current version to identify deleted objects.
6. Splitting `target` into `target_client`/`target_service`/`target_plugin` is a good idea. I think `target_plugin` corresponds to what I currently refer to as `target`.
   The current document only provides a schematic representation of the process for the `target` part. Due to space management and interface differences, I do not want to create a highly abstract unified structure in the `target` module, as that could be quite challenging.
   My current idea is to define only a few coarse-grained interfaces, pass in the metadata, and let `target` allocate and manage the storage space according to its own needs. The specific data is then read into the corresponding storage space through the read interface provided by the `engine` module.
   As the project matures, it might be a better choice to classify and abstract `target`.
7. `CheckPointMetaBuilder` will indeed be a relatively complex component. My current idea is to implement it in a basic library `framework` since all three modules might depend on it.
   * However, each `source` and `target` is different, and their `Meta` information is also different. It will require many extension fields to store their custom attributes.
   * Defining everything completely from the start is challenging. I plan to first create a rough definition and iterate and upgrade it subsequently to form a more complete version before release.
8. `export` should indeed be scheduled for later stages. While considering local data storage, I thought of this requirement and wrote it down briefly.
   * Speaking of storage, I think we can still use databases like `mysql` or `sqlite`. When exporting, we can write the useful information from the database into a `toml` text file.

**Comment by streetycat** [comment]
I have defined the meta in new commit

**Comment by waterflier** [comment]
The code in the design document is quite extensive, and I'm trying to understand the core logic. I believe the core process is something like this:

```javascript
function run_backup(source_plugin, source_url, target_plugin, target_url) {
    meta_db = get_meta_db(source_url, target_url);
    check_point = target_plugin.get_last_check_point(source_url, target_url);

    for (item in source_plugin.get_reader(source_url).next()) {
        // This check is for deduplication / calculating diffs
        // Performance would be better if it relies on local check_point cache
        action = target_plugin.check_action(item, check_point)
        meta_db.insert(item, action);
    }

    for (item, action in meta_db.next()) {
        // We should design Action based on NamedObject experience to improve performance
        // Enhance the performance of writing data to the Target
        await do_action(item, action, source_plugin, target_plugin)
    }
}
```

**Comment by streetycat** [comment]
> The code in the design document is quite extensive, and I'm trying to understand the core logic. I believe the core process is something like this:
> 
> ```js
> function run_backup(source_plugin, source_url, target_plugin, target_url) {
>     meta_db = get_meta_db(source_url, target_url);
>     check_point = target_plugin.get_last_check_point(source_url, target_url);
> 
>     for (item in source_plugin.get_reader(source_url).next()) {
>         // This check is for deduplication / calculating diffs
>         // Performance would be better if it relies on local check_point cache
>         action = target_plugin.check_action(item, check_point)
>         meta_db.insert(item, action);
>     }
> 
>     for (item, action in meta_db.next()) {
>         // We should design Action based on NamedObject experience to improve performance
>         // Enhance the performance of writing data to the Target
>         await do_action(item, action, source_plugin, target_plugin)
>     }
> }
> ```

Thank you for your concise and accurate summary. I have included some thoughts on the implementation in the documentation. Now, I have split it further and created a separate document specifically for the definition of the `Meta` data structure.

In your code snippet:
```rust
    for (item in source_plugin.get_reader(source_url).next()) {
        // This check is for deduplication / calculating diffs
        // Performance would be better if it relies on local check_point cache
        action = target_plugin.check_action(item, check_point)
        meta_db.insert(item, action);
    }
```

This part corresponds to `engine.prepare_checkpoint`.

In the following snippet:
```rust
    for (item, action in meta_db.next()) {
        // We should design Action based on NamedObject experience to improve performance
        // Enhance the performance of writing data to the Target
        await do_action(item, action, source_plugin, target_plugin)
    }
```

This part corresponds to `target.start_transfer_checkpoint`.

Your abstraction of `target_plugin.check_action` is excellent and can support different `Service` implementations with various incremental strategies. I have added the relevant interface `target.diff` in the new documentation. However, this process can be quite complex (considering local cache and transmission costs). In the first phase, we can skip this and simply replace old files with new ones.

**Comment by streetycat** [comment]
I have make a plan in new commit.

**Comment by alexsunxl** [comment]
Has this part of the UI been confirmed? I would want to take responsibility for the development of this section.

@streetycat @waterflier

**Comment by waterflier** [comment]
> Has this part of the UI been confirmed? I would want to take responsibility for the development of this section.
> 
> @streetycat @waterflier

Follow our progress, you would create a pull request include your Design and Plan about the webUI modules. And we can talking about 'PRD confirm' at that issue~ I expect you to raise questions about the requirements from the perspective of implementation (there is definitely room for self-expression in many details now), and you can also improve some details according to your own ideas, but you need to write the document first.

**Comment by photosssa** [comment]
Regarding the framework, there are several questions:

    How is the meta db backed up?
    What are the constraints and interfaces for the target plugin?
    Does the implementation of the source plugin depend on the capabilities of the target plugin, such as whether the target supports structured storage (e.g., key-value storage), whether the target is trustworthy (whether the source needs encryption), and whether the target itself is verifiable (whether it needs to be signed by the source)? If the framework supports backing up from a single source to multiple targets, should different-capability targets generate different backups, or should they produce similar backups based on the lowest capability?
    If encryption is required for the backup, what key should be used? If the target itself has a decentralized key (such as dmcx), it should be used directly; if the target does not have one, should an additional key be generated for the backup, and how should the backup key be managed and backed up? If the source simultaneously backs up to multiple targets, including dmcx targets, should each use its own key, or should they all use the dmcx key?

**Comment by streetycat** [comment]
I have finished the interface define, and the database.

**Comment by streetycat** [comment]
> Regarding the framework, there are several questions:
> 
> 1. How is the meta db backed up?
> 2. What are the constraints and interfaces for the target plugin?
> 3. Does the implementation of the source plugin depend on the capabilities of the target plugin, such as whether the target supports structured storage (e.g., key-value storage), whether the target is trustworthy (whether the source needs encryption), and whether the target itself is verifiable (whether it needs to be signed by the source)? If the framework supports backing up from a single source to multiple targets, should different-capability targets generate different backups, or should they produce similar backups based on the lowest capability?
> 4. If encryption is required for the backup, what key should be used? If the target itself has a decentralized key (such as dmcx), it should be used directly; if the target does not have one, should an additional key be generated for the backup, and how should the backup key be managed and backed up? If the source simultaneously backs up to multiple targets, including dmcx targets, should each use its own key, or should they all use the dmcx key?

Here are my points:

1. Metadata is generally stored locally in the form of a database, which can be exported to generate text and then imported. In extreme cases, we should store metadata in the `target` during backup and recover data by scanning the contents stored in the `target` when local information is lost. This process might be relatively slow.
2. In my latest commit, I have included the interface definitions for each module. Feel free to join the discussion.
3. `source` and `target` should refer to the same storage medium during the backup and recovery processes, respectively. A `target` should have a corresponding `source` to support the recovery of its stored contents.
4. For `targets` with different storage methods, I believe it is unnecessary to store exactly the same content. The important thing is that, regardless of how they are stored, they should be able to produce identical data upon recovery. Trust and verification should be determined based on the specific requirements of the `target` that the developer wants to implement.
5. I think each `target` should not create dependencies. They should have their own authentication and encryption methods because they are different from each other. For now, I have not considered adding related requirements to the framework, as it might be too abstract and increase the difficulty of understanding. `DMCX` might also need to design its sector structure format to store metadata and file content. For encryption, I think adding an `AES` key encrypted with a private key in the sector would suffice.

**Pull request merged**
